sudo: required

language: go
go:
    - 1.8

before_install:
    - sudo apt-get install cgroup-bin
    - go get github.com/smartystreets/goconvey
    - go get golang.org/x/tools/cmd/cover
    - go get -v github.com/mattn/goveralls

os:
    - linux

services:
    - docker

before_script:
    - lssubsys -am
    - sudo cgcreate -a $USER -t $USER -g cpu:tunasync
    - sudo cgcreate -a $USER -t $USER -g memory:tunasync
    - docker pull alpine

script:
    - ./.testandcover.bash

after_success:
    - goveralls -coverprofile=profile.cov -service=travis-ci

before_deploy: "echo 'ready to deploy?'"

deploy:
    provider: releases
    file:
        - "build/tunasync-linux-bin.tar.gz"
    api_key:
        secure: "F9kaVaR1mxEh2+EL9Nm8GZmbVY98pXCJA0LGDNrq1C2vU61AUNOeX6yI1mMklHNZPLBqoFDvGN1M5HnJ+xWCFH+KnJgLD2GVIAcAxFNpcNWQe8XKE5heklNsIQNQfuh/rJKM6YzeDB9G5RN4Y76iL4WIAXhNnMm48W6jLnWhf70="
    skip_cleanup: true
    overwrite: true
    on:
        tags: true
        all_branches: true
