sudo: required

language: go
go:
    - 1.8

before_install:
    - sudo apt-get install cgroup-bin
    - go get github.com/smartystreets/goconvey
    - go get golang.org/x/tools/cmd/cover
    - go get -v github.com/mattn/goveralls

os:
    - linux

services:
    - docker

before_script:
    - lssubsys -am
    - sudo cgcreate -a $USER -t $USER -g cpu:tunasync
    - sudo cgcreate -a $USER -t $USER -g memory:tunasync
    - docker pull alpine

script:
    - ./.testandcover.bash

after_success:
    - goveralls -coverprofile=profile.cov -service=travis-ci

before_deploy: "echo 'ready to deploy?'"

deploy:
    provider: releases
    file:
        - "build/tunasync-linux-bin.tar.gz"
    api_key:
        secure: ZOYL/CALrVJsZzbZqUMSI89Gw4zsBJH1StD/2yTyG45GfKgvtK4hG0S5cQM/L0wcikjEkgxSMsmr4ycq+OwbN++gc0umfoAQ/VSjzetiobAlT1E854aRKRjT82WxYdnPW2fsFjuEJTcyZmcbgJGTMi86MDt7w8tEjLomhd1+rUo=
    skip_cleanup: true
    overwrite: true
    on:
        tags: true
        all_branches: true
        repo: tuna/tunasync
